#!/bin/sh

symbol() {
[ $(cat /sys/class/net/w*/operstate) = down ] && echo  && exit
echo 
}

name() {
ip addr | grep 'state UP' -A2 | tail -n1 | awk '{print $2}' | cut -f1  -d'/'
}

[ "$1" = "icon" ] && symbol && exit
[ "$1" = "name" ] && name && exit
