name: "Build and Cache Outputs"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Nix
      uses: cachix/install-nix-action@v31.10.1
      with:
        extra_nix_config: |
          experimental-features = nix-command flakes
          extra-platforms = aarch64-linux
    - name: Set up QEMU ARM64
      uses: docker/setup-qemu-action@v4.0.0
      with:
        platforms: arm64
    - name: Restore and save Nix Store
      uses: nix-community/cache-nix-action@v7
    - name: Setup Nix binary cache
      run: nix run .#setup-nix-cache
    - name: Build desktop Nix config
      run: |
        nix build \
          .#nixosConfigurations.peter-pc.config.system.build.toplevel \
          --out-link result-nixos
    - name: Build nix-on-droid config
      run: |
        nix build \
          .#nixOnDroidConfigurations.a15.activationPackage \
          --out-link result-nod
    - name: Setup SSH Agent
      uses: webfactory/ssh-agent@v0.10.0
      with:
        ssh-private-key: ${{ secrets.NIX_SSH_PRIVATE_KEY }}
    - name: Copy Nix paths to remote server
      run: |
        nix copy --to "${{ vars.NIX_REMOTE_HOST }}" result-nixos result-nod
      if: ${{ vars.NIX_REMOTE_HOST != '' }}
